version: '3.9'

networks:
  stormnet:
    external: true

services:
  zookeeper:
    image: zookeeper
    networks:
      - stormnet
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.hostname==anaconda'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nimbus:
    image: storm:2.3.0
    command: storm nimbus
    networks:
      - stormnet
    ports:
      - 6627:6627
    volumes:
      - /home/valentina/jars:/jars
      - /home/valentina/custom_scheduler.jar:/apache-storm-2.3.0/lib/custom_scheduler.jar
      - /home/valentina/nimbus.yaml:/conf/storm.yaml
      - /home/valentina/nimbus_logs:/apache-storm-2.3.0/logs
    deploy:
      placement:
        constraints:
          - 'node.hostname==anaconda'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        
  ui:
    image: storm:2.3.0
    command: storm ui
    networks:
      - stormnet
    volumes:
      - /home/valentina/nimbus.yaml:/conf/storm.yaml
      - /home/valentina/ui_logs:/apache-storm-2.3.0/logs
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints:
          - 'node.hostname==anaconda'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  supervisor:
    image: storm:2.3.0
    command: storm supervisor
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    networks:
      - stormnet
    ports:
      - 6700:6700
      - 6701:6701
      - 6702:6702
      - 6703:6703
      - 6704:6704
    volumes:
      - /home/valentina/supervisor.yaml:/conf/storm.yaml
      - /home/valentina/logs:/apache-storm-2.3.0/logs
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3     
